"""initial

Revision ID: 1bacfe71af33
Revises: 4c16831d7168
Create Date: 2024-10-08 18:55:45.189523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bacfe71af33'
down_revision: Union[str, None] = '4c16831d7168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_profiles_user_fkey', 'users_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'users_profiles', 'users', ['user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_profiles', type_='foreignkey')
    op.create_foreign_key('users_profiles_user_fkey', 'users_profiles', 'users', ['user'], ['id'])
    # ### end Alembic commands ###
