"""initial

Revision ID: 4c16831d7168
Revises: a4b6ee25c8a6
Create Date: 2024-10-08 18:47:10.050528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c16831d7168'
down_revision: Union[str, None] = 'a4b6ee25c8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profiles', sa.Column('user', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_users_profiles_user'), 'users_profiles', ['user'], unique=False)
    op.create_foreign_key(None, 'users_profiles', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_users_profiles_user'), table_name='users_profiles')
    op.drop_column('users_profiles', 'user')
    # ### end Alembic commands ###
