"""initial

Revision ID: 5886b63ba36d
Revises: 1bacfe71af33
Create Date: 2024-10-08 20:31:23.607745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5886b63ba36d'
down_revision: Union[str, None] = '1bacfe71af33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profiles', sa.Column('notification_vk', sa.Boolean(), nullable=True))
    op.add_column('users_profiles', sa.Column('mailing_mail', sa.Boolean(), nullable=True))
    op.add_column('users_profiles', sa.Column('auth2', sa.Boolean(), nullable=True))
    op.add_column('users_profiles', sa.Column('access_catalog', sa.Boolean(), nullable=True))
    op.add_column('users_profiles', sa.Column('closed_profile', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_profiles', 'closed_profile')
    op.drop_column('users_profiles', 'access_catalog')
    op.drop_column('users_profiles', 'auth2')
    op.drop_column('users_profiles', 'mailing_mail')
    op.drop_column('users_profiles', 'notification_vk')
    # ### end Alembic commands ###
