"""initial

Revision ID: 81032e827731
Revises: 9bcb484af767
Create Date: 2024-10-10 22:19:41.469213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81032e827731'
down_revision: Union[str, None] = '9bcb484af767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'creators', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'creators', type_='unique')
    # ### end Alembic commands ###
