"""initial

Revision ID: 9bcb484af767
Revises: a27d3603ef20
Create Date: 2024-10-10 21:48:15.986424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcb484af767'
down_revision: Union[str, None] = 'a27d3603ef20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genre_books', ['book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre_books', type_='unique')
    # ### end Alembic commands ###
