"""initial

Revision ID: c0b5f4a34431
Revises: cf10dd6d9028
Create Date: 2024-10-06 16:14:29.961001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b5f4a34431'
down_revision: Union[str, None] = 'cf10dd6d9028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'img',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'img',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
