"""initial

Revision ID: cf10dd6d9028
Revises: c7cb1719a1b1
Create Date: 2024-10-06 16:13:48.207999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf10dd6d9028'
down_revision: Union[str, None] = 'c7cb1719a1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img')
    # ### end Alembic commands ###
